[package]
name = "gpio-rs"
version = "0.1.0"
authors = ["nomyfan <Nomyfan@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap2 = "0.2.2"

[features]
default = ["pi4"]
pi4 = []
oths = []